"""create tables

Revision ID: 4ebad79f6fc3
Revises: 
Create Date: 2024-05-25 09:12:01.361761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebad79f6fc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercializacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exportacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cultivar', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('producao')
    op.drop_table('processamento')
    op.drop_table('importacao')
    op.drop_table('exportacao')
    op.drop_table('comercializacao')
    # ### end Alembic commands ###
